name: "Setup chart testing environment"
description: "Action which sets up Helm chart testing environment, optionally also installing specific Kubernetes version using minikube"

inputs:
  minikube_version:
    description: "Minikube version to use"
    required: false
    default: "v1.27.1"
  k8s_version:
    description: "Kubernetes version to be installed by minikube (if any)"
    required: false
    default: ""
  github_token:
    description: "Github token to use for communication with Github API to avoid rate limits"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Helm
      id: setup-helm
      uses: azure/setup-helm@b5b231a831f96336bbfeccc1329990f0005c5bb1 # v3.3
      with:
        version: "latest"

    - uses: actions/setup-python@v4
      id: setup-python
      with:
        python-version: 3.8

    - name: Set up chart-testing
      id: setup-chart-testing
      uses: helm/chart-testing-action@09ed88797198755e5031f25be13da255e7e33aad  # v2.3.0
      with:
        version: v3.7.0

    - name: Create minikube Kubernetes ${{ inputs.k8s_version }} Cluster
      id: create-minikube-cluster
      if: ${{ inputs.k8s_version != '' }}
      uses: manusa/actions-setup-minikube@a36e52547d6fb013f8873758b695ae97a353377b # v2.7.0
      with:
        minikube version: '${{ inputs.minikube_version }}'
        kubernetes version: '${{ inputs.k8s_version }}'
        start args: '--wait=all'
        github token: '${{ inputs.github_token }}'

    - name: Print minikube environment info
      id: print-k8s-cluster-info
      if: ${{ inputs.k8s_version != '' }}
      shell: bash
      run: |
        # Workaround for occasional DNS issues
        # kubectl -n kube-system rollout restart deployment coredns
        kubectl version
        minikube addons list
        kubectl get nodes
        kubectl cluster-info
        kubectl get pods -A
