name: "Helm Lint, Install and Tests"
description: "Action which runs helm lint and install and tests the chart"

inputs:
  k8s_version:
    description: "Kubernetes version to be installed by minikube"
    required: true
    default: "v1.17.2"
  github_token:
    description: "Github token to use for communication with Github API to avoid rate limits"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Helm
      uses: azure/setup-helm@18bc76811624f360dbd7f18c2d4ecb32c7b87bab # v1.1
      with:
        version: v3.7.0

    - uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Set up chart-testing
      uses: helm/chart-testing-action@5f16c27cf7a4fa9c776ff73734df3909b2b65127 # v2.1.0
      with:
        version: v3.4.0

    - name: Create minikube Kubernetes ${{ matrix.k8s_version }} Cluster
      uses: manusa/actions-setup-minikube@3cce81c968cabc530141d5620b7d9942a2907df5 # v2.4.2
      with:
        minikube version: 'v1.23.2'
        kubernetes version: '${{ inputs.k8s_version }}'
        github token: '${{ inputs.github_token }}'

    - name: Print minikube environment info
      shell: bash
      run: |
        kubectl -n kube-system rollout restart deployment coredns
        kubectl version
        minikube addons list
        sleep 5

    - name: Run chart-testing (install)
      shell: bash
      env:
      # We perform just the chart install and not full end to end test here so
      # we don't use a valid API key.
        API_KEY: "dummy"
      run: |
        ct install --debug --config ci/ct.yaml

        # - name: Run chart-testing (install) - deployment controller type
        #   env:
        #   # We perform just the chart install and not full end to end test here so
        #   # we don't use a valid API key.
        #     API_KEY: "dummy"
        #   run: |
        #     # Write test values to a file which is used by ct install
        #     mkdir -p charts/scalyr-agent/ci/
        #     echo -e 'controllerType: "deployment"\nscalyr:\n  apiKey: "${API_KEY}"' > charts/scalyr-agent/ci/test-values.yaml

        #     ct install --debug --config ci/ct.yaml
