apiVersion: v1
kind: Secret
metadata:
  name: {{ include "scalyr-helm.fullname" . }}-scalyr-api-key
  labels:
  {{- include "scalyr-helm.labels" . | nindent 4 }}
data:
  scalyr-api-key: {{ .Values.scalyr.apiKey }}
