# Values file used by end to end tests
controllerType: "daemonset"
podLabels:
  test: "true"
extraEnvVars:
  - name: SCALYR_FOO_1
    value: "foo1"
  - name: SCALYR_BAR_2
    value: "bar2"
scalyr:
  apiKey: "REPLACE_ME"
  k8s:
    clusterName: "k8s-explorer-e2e-tests"
    verifyKubeletQueries: false
  base64Config: true
  config:
    # ci/examples/agent.d/test-config.json
    test-config.json: e3NlcnZlcl9hdHRyaWJ1dGVzOiB7YXR0cmlidXRlMTogInZhbHVlMSIsYXR0cmlidXRlMjogInZhbHVlMiIsfSx9

volumes:
  - name: test-volume
    emptyDir: {}

volumeMounts:
  - mountPath: /test-volume
    name: test-volume

image:
  distro: "IMAGE_TYPE"
