# Values file used by end to end tests
controllerType: "deployment"
podLabels:
  test: "true"
scalyr:
  apiKey: "REPLACE_ME"
  k8s:
    clusterName: "k8s-explorer-e2e-tests"
    verifyKubeletQueries: false
  base64Config: true
  config:
    # ci/examples/agent.d/test-config.json
    test-config.json: e3NlcnZlcl9hdHRyaWJ1dGVzOiB7YXR0cmlidXRlMTogInZhbHVlMSIsYXR0cmlidXRlMjogInZhbHVlMiIsfSx9

useRawApiKeyEnvValue: true

volumes:
  - name: test-volume
    emptyDir: {}

volumeMounts:
  - mountPath: /test-volume
    name: test-volume
